app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('products.urls')),
]

suppliers/urls.py
from django.urls import path
from .views import (
        SupplierListView, SupplierCreateView, SupplierUpdateView,
        SupplierDetailView, SupplierDeleteView
    )

urlpatterns = [
    path(
        'supplier/list/', SupplierListView.as_view(), name='supplier_list'
    ),
    path(
        'supplier/create/', SupplierCreateView.as_view(),
        name='supplier_create'
    ),
    path(
        'supplier/<int:pk>/update', SupplierUpdateView.as_view(),
        name='supplier_update'
    ),
    path(
        'supplier/<int:pk>/detail', SupplierDetailView.as_view(),
        name='supplier_detail'
    ),
    path(
        'supplier/<int:pk>/delete', SupplierDeleteView.as_view(),
        name='supplier_delete'
    ),
]

categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

suppliers/models.py
from django.db import models


class Supplier(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

suppliers/forms.py
from .models import Supplier
from django import forms


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            }),
        }
        labels = {
            'name': 'Nome',
            'description': 'Descrição'
        }

suppliers/views.py
from django.views.generic import (
    ListView, CreateView, DeleteView, DetailView, UpdateView
)
from django.urls import reverse_lazy
from .models import Supplier
from .forms import SupplierForm


class SupplierListView(ListView):
    model = Supplier
    template_name = 'supplier_list.html'
    context_object_name = 'suppliers'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')

        if name:
            queryset = queryset.filter(name__icontains=name)

        return queryset


class SupplierCreateView(CreateView):
    model = Supplier
    template_name = 'supplier_create.html'
    form_class = SupplierForm
    success_url = reverse_lazy('supplier_list')


class SupplierUpdateView(UpdateView):
    model = Supplier
    template_name = 'supplier_update.html'
    form_class = SupplierForm
    success_url = reverse_lazy('supplier_list')


class SupplierDetailView(DetailView):
    model = Supplier
    template_name = 'supplier_detail.html'


class SupplierDeleteView(DeleteView):
    model = Supplier
    template_name = 'supplier_delete.html'
    success_url = reverse_lazy('supplier_list')

suppliers/templates/supplier_create.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-6">Cadastrar Fornecedor</h3>

        <div class="card">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary">
                        Salvar Fornecedor
                    </button>
                </form>
            </div>
        </div>
        <a href="{% url "supplier_list" %}" class="btn btn-secondary mt-3">
            Cancelar e Voltar para a lista de Fornecedores
        </a>
    </div>
{% endblock content %}

suppliers/templates/supplier_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-6">Deletar Fornecedor</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">
                    Tem certeza que deseja excluir o Fornecedor <strong>{{object.name}}</strong>
                </p>

                <form method="post" action="">
                    {% csrf_token %}

                    <button type="submit" class="btn mt-3 btn-danger">Confirmar</button>
                </form>
                <a href=" {% url "category_list" %}" class="btn btn-secondary mt-3">
                    Voltar para a Lista de Fornecedores
                </a>
            </div>
        </div>
        
    </div>
{% endblock content %}

suppliers/templates/supplier_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-6">Detalhes do Fornecedor</h3>

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{object.name}}</h3>
                <p class="card-text">
                    {{object.description}}
                </p>
            </div>
        </div>
        <a href=" {% url "supplier_list" %}" class="btn btn-secondary mt-3">
            Voltar para a Lista de Fornecedores
        </a>
    </div>
{% endblock content %}

suppliers/templates/supplier_list.html
{% extends "base.html" %}

{% block title %}SGE- Categorias{% endblock title %}

{% block content %}
    <div class="row mb-3">
        <div class="col-md-6">
            <form action="{% url "supplier_list" %}" method="get">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" value={{request.GET.name}}>
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-search"></i>
                    </button>
                </div>
            </form>
        </div>

        <div class="col-md-6">
            <a href="{% url "supplier_create" %}" class="btn btn-success float-end">
                <i class="bi bi-plus">Novo Fornecedor</i>
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <td>Nome</td>
                    <td>Descrição</td>
                </tr>
            </thead>
            <tbody>
                {% for supplier in suppliers %}
                    <td>{{supplier.id}}</td>
                    <td>{{supplier.name}}</td>
                    <td>{{supplier.description}}</td>
                    <td class="text-center">
                        <a href="{% url "supplier_detail" supplier.id %}" class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i>
                        </a>

                        <a href="{% url "supplier_update" supplier.id%}" class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i>
                        </a>

                        <a href="{% url "supplier_delete" supplier.id%}" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "components/pagination.html" %}
{% endblock content %}

suppliers/templates/supplier_update.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-4">Editar Fonecedor</h3>

        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary">
                        Salvar Fornecedor
                    </button>
                </form>
            </div>
        </div>
        <a href=" {% url "supplier_list" %}" class="btn btn-secondary mt-3">
            Cancelar e Voltar para a Lista de Fornecedores
        </a>
    </div>
{% endblock content %}